// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbeojjqarkkhisdrlbmk.supabase.co";

const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiZW9qanFhcmtraGlzZHJsYm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3NjA2MjUsImV4cCI6MjA4NTMzNjYyNX0.DlDuar7hI6kvZapVM1E7QqFK0Q4DaEiEfSwoYuAtFSE";

// ✅ Correct config for static site (GitHub Pages)
// prevents random failures / missing data / session errors

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
      detectSessionInUrl: false,
    },
    global: {
      fetch: (...args) => fetch(...args),
    },
  }
);
